### ISSUE TITLE
Getting the permission denied when running commands with Docker on Visual Studio Code.

### ISSUE THREAD

**Issue by MerrySonoely-FS** [jworkman/ASL-Knowledge-Base#7]
# Issue Description

Docker issue where suddenly my permission to run commands was denied by Docker. I could not resolve this on my own, but if you would instruct me how to I will be able to record a video of my commands running. Here's a screenshot of the issue in the terminal. 

# Full Error Backtrace

# Screenshots

<img width="696" alt="Screenshot 2024-04-16 at 2 20 51 AM" src="https://github.com/jworkman/ASL-Knowledge-Base/assets/137943977/a02e5218-43f1-4d73-aae2-22534ae7ab33">

# Any Other Notes

**Comment by jworkman** [comment]
Hi Sonoely,

Looks like you missed the last portion of this ticket which was any research performed on this specific issue that was performed. 

Based on your screenshot it looks like you might be assigning different file permission/ownership settings either to the files being copied into your Docker containers, or the file ownership permissions are being modified in your Dockerfile. I'm not sure since your screenshot gives me very little information. 

I believe I wrote you an email a few days ago about meeting with me via zoom sometime this week. Please respond back to me in that email so that we can setup a date/time to meet.
